# Generated by Django 2.1.3 on 2018-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('is_super', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], verbose_name='is super')),
                ('status', models.IntegerField(choices=[(0, 'normal'), (1, 'frozen'), (2, 'cancelled')], verbose_name='status')),
                ('last_login_time', models.DateTimeField(verbose_name='last login time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('mobile', models.CharField(max_length=20, verbose_name='mobile')),
                ('github_account', models.CharField(max_length=64, verbose_name='github account')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('creator_id', models.CharField(max_length=20, verbose_name='creator id')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
    ]
